### PR TITLE
Another fine present for 1.0.0 - HTTPClient

### PR DESCRIPTION
**Pull request by johnny-bit**
Hi!

Some fine folks asked for one, but somehow I never got a round tuit to polish my HTTPClient. Now I have.

I know changeset reads like bad poetry and there are no tests (yet), but trust me - this is fine. I've been running that on production for a bit now :)

### CODE REVIEW

**Comment by johnny-bit** [comment]
Can we somehow get styleci & scruntizer code style, so that one could configure IDE autoformatting to avoid hitting styleci BS? Also - it seems that styleci & scruntizer aren't compatible enough ;)

**Comment by lifeofguenter** [comment]
awesome stuff again @johnny-bit - I can fully agree with this PR as its not changing the principle of xml based input/output but just adding a different client layer! Love it :)

ignore scrutinizer + codecov for now, the whole client.php needs some refactoring.. 👍

**Comment by johnny-bit** [comment]
> ignore scrutinizer + codecov for now, the whole client.php needs some refactoring

Heh. doingit :D

**Comment by johnny-bit** [comment]
OK, this should be ready to merge.

**Pull request merged**
