### PR TITLE
Allow to set extension name manually

### PR DESCRIPTION
**Pull request by jkaflik**
I faced with the limitation on extension node in XML document as it's required by **AbstractFrame** to have same name as extension class. Simply, for my registrar it's a _extdom_ for all actions on each domain, and I wanted to have more clarified naming.
I think it would be also helpfully for someone else.

Features:
- added _getExtensionName_ in **ExtensionInterface**
- default implementation of _getExtensionName_ in **AbstractFrame** with previously implemented mechanism

BTW. There is also one commit which takes a git ignore on IntelliJ project files.

### CODE REVIEW

**Comment by lifeofguenter** [comment]
Thanks a lot for your contribution :)

This looks like a cleaner implementation, but I already had a check:

```
if (!isset($this->extension)) {
```

Meaning, to override the default behaviour you just had to set the property: $extension :)

In this case, You can actually remove that check - but it would be a regression and I would have to still have to check/modify the internal classes of this project to reflect that change.

**Comment by jkaflik** [comment]
Hello after one year :)

@lifeofguenter have you considered to merge this PR?

**Comment by jkaflik** [comment]
@lifeofguenter Also understood what you are about:

> Meaning, to override the default behaviour you just had to set the property: $extension :)

I can agree with you, but it's not explicit behaviour. Also I been familiar with that, and for some reason I had to refactor it such way.

**Comment by lifeofguenter** [comment]
Shit sorry, this has been unattended by me for far too long - would you mind fixing the merge conflicts? Then I can merge into master right away.

**Comment by jkaflik** [comment]
@lifeofguenter Done :)

**Comment by lifeofguenter** [comment]
Thanks so much for your contribution @jkaflik and sorry again for the long-ass time to merge this in!

**Pull request merged**
