### PR TITLE
Add Nominet release extension

### PR DESCRIPTION
**Pull request by greenmato**
Adds Nominet's release extension.
See docs:
https://registrars.nominet.uk/namespace/uk/registration-and-domain-management/epp-commands#release

### CODE REVIEW

**Comment by johnny-bit** [comment]
Fix your tests :)

```
There was 1 error:
1) AfriCC\Tests\EPP\Extension\Nominet\Release\DomainTest::test
Error: Class 'AfriCC\EPP\Extension\Nominet\Release\Domain' not found
/home/travis/build/AfriCC/php-epp2/tests/EPP/Extension/Nominet/Release/DomainTest.php:14
```

**Comment by greenmato** [comment]
> Fix your tests :)

Fixed 🤙

**Comment by greenmato** [comment]
@johnny-bit any chance this could be merged?

**Comment by johnny-bit** [comment]
I am not authorized to merge PRs. I'm just a contributor like you ;)

@lifeofguenter - can you please merge and/or add me to authorized people ;)

**Review by lifeofguenter — APPROVED** [review]

**Comment by johnny-bit** [comment]
Hey @greenmato  - nominet has quite a few extensions, would you mind adding new PRs for them? It would be great to have all of them available :)

**Pull request merged**
