### PR TITLE
Fixed poor logic which prevents verify_peer_name from being set to false

### PR DESCRIPTION
**Pull request by domainregistrar**
empty() considers false to be empty, so it was not possible to set verify_peer_name to false as was changed to true due to the check.

See: http://php.net/manual/en/function.empty.php

isset() should be used here to ensure the option is taken into account when set.

### CODE REVIEW

**Comment by domainregistrar** [comment]
I'm not sure what coverage check is complaining about, seems to be a file I didn't even edit?

**Comment by johnny-bit** [comment]
Don't worry about coveralls. Should be fine. Dunno why it picked it up now though :/

**Comment by domainregistrar** [comment]
> Don't worry about coveralls. Should be fine. Dunno why it picked it up now though :/

Ah good, I won't worry then, hopefully someone will merge it in. =]

**Comment by lifeofguenter** [comment]
Thanks @domainregistrar

**Pull request merged**
